server:
  port: ${SERVER_PORT:8080}
management:
  endpoints:
    web:
      exposure:
        include: "info,prometheus"
      path-mapping:
        prometheus: "/metrics"
  metrics:
    export:
      prometheus:
        enabled: true
grpc:
  server:
    port: ${GRPC_SERVER_PORT:9090}
spring:
  datasource:
    url: ${POSTGRES_DB_URL:jdbc:postgresql://localhost:5432/vogorode}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123}
