server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: "info,prometheus"
      path-mapping:
        prometheus: "/metrics"
  metrics:
    export:
      prometheus:
        enabled: true
grpc:
  client:
    HandymanService:
      address: "localhost:9090"
      negotiation-type: PLAINTEXT
    RancherService:
      address: "localhost:9091"
      negotiation-type: PLAINTEXT
