server:
  port: ${PORT:8082}
management:
  endpoints:
    web:
      exposure:
        include: "info,prometheus"
      path-mapping:
        prometheus: "/metrics"
  metrics:
    export:
      prometheus:
        enabled: true
grpc:
  client:
    HandymanService:
      address: ${HANDYMAN_GRPC-SERVER_ADDRESS:localhost:9090}
      negotiation-type: PLAINTEXT
    RancherService:
      address: ${RANCHER_GRPC_SERVER_ADDRESS:localhost:9091}
      negotiation-type: PLAINTEXT
